-- 코드를 입력하세요
SELECT A.BOOK_ID,B.AUTHOR_NAME, SUBSTRING(A.PUBLISHED_DATE,1, 10) AS PUBLISHED_DATE
FROM BOOK A
inner JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE